
package cn.tellyouwhat.gradeteller.murpnewsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MURPNewsServiceSoap", targetNamespace = "http://murpcn.com/murpwebservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MURPNewsServiceSoap {


    /**
     * 课堂点名-当天课表
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetDmScheduList", action = "http://murpcn.com/murpwebservice/GetDmScheduList")
    @WebResult(name = "GetDmScheduListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetDmScheduList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetDmScheduList")
    @ResponseWrapper(localName = "GetDmScheduListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetDmScheduListResponse")
    public ArrayOfPublicStruct getDmScheduList(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid);

    /**
     * 课堂点名-发起课堂点名(获取验证码)
     * 
     * @param dd
     * @param jxbId
     * @param teacherId
     * @param teacherName
     * @param lessonId
     * @param jc
     * @param jxbName
     * @param lessonName
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetqdAuthCode", action = "http://murpcn.com/murpwebservice/GetqdAuthCode")
    @WebResult(name = "GetqdAuthCodeResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetqdAuthCode", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetqdAuthCode")
    @ResponseWrapper(localName = "GetqdAuthCodeResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetqdAuthCodeResponse")
    public ArrayOfPublicStruct getqdAuthCode(
        @WebParam(name = "lesson_id", targetNamespace = "http://murpcn.com/murpwebservice/")
        String lessonId,
        @WebParam(name = "lesson_name", targetNamespace = "http://murpcn.com/murpwebservice/")
        String lessonName,
        @WebParam(name = "jxb_id", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jxbId,
        @WebParam(name = "jxb_name", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jxbName,
        @WebParam(name = "teacher_id", targetNamespace = "http://murpcn.com/murpwebservice/")
        String teacherId,
        @WebParam(name = "teacher_name", targetNamespace = "http://murpcn.com/murpwebservice/")
        String teacherName,
        @WebParam(name = "jc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jc,
        @WebParam(name = "dd", targetNamespace = "http://murpcn.com/murpwebservice/")
        String dd);

    /**
     * 课堂点名-[学生获取点名签到状态]
     * 
     * @param kcid
     * @param weeknum
     * @param week
     * @param umcid
     * @param xnxq
     * @param jieci
     * @param bid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DmStuGetState", action = "http://murpcn.com/murpwebservice/DmStuGetState")
    @WebResult(name = "DmStuGetStateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "DmStuGetState", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmStuGetState")
    @ResponseWrapper(localName = "DmStuGetStateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmStuGetStateResponse")
    public String dmStuGetState(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "kcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String kcid,
        @WebParam(name = "bid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String bid,
        @WebParam(name = "weeknum", targetNamespace = "http://murpcn.com/murpwebservice/")
        String weeknum,
        @WebParam(name = "week", targetNamespace = "http://murpcn.com/murpwebservice/")
        String week,
        @WebParam(name = "jieci", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jieci,
        @WebParam(name = "xnxq", targetNamespace = "http://murpcn.com/murpwebservice/")
        String xnxq);

    /**
     * 课堂点名-[教师获取点名签到状态]
     * 
     * @param kcid
     * @param weeknum
     * @param week
     * @param umcid
     * @param xnxq
     * @param jieci
     * @param bid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "DmTeaGetState", action = "http://murpcn.com/murpwebservice/DmTeaGetState")
    @WebResult(name = "DmTeaGetStateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "DmTeaGetState", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmTeaGetState")
    @ResponseWrapper(localName = "DmTeaGetStateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmTeaGetStateResponse")
    public ArrayOfPublicStruct dmTeaGetState(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "kcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String kcid,
        @WebParam(name = "bid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String bid,
        @WebParam(name = "weeknum", targetNamespace = "http://murpcn.com/murpwebservice/")
        String weeknum,
        @WebParam(name = "week", targetNamespace = "http://murpcn.com/murpwebservice/")
        String week,
        @WebParam(name = "jieci", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jieci,
        @WebParam(name = "xnxq", targetNamespace = "http://murpcn.com/murpwebservice/")
        String xnxq);

    /**
     * 课堂点名-[学生签到]
     * 
     * @param authcode
     * @param umcid
     * @param qdztid
     * @param latitude
     * @param longitude
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Checkin_stu", action = "http://murpcn.com/murpwebservice/Checkin_stu")
    @WebResult(name = "Checkin_stuResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Checkin_stu", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CheckinStu")
    @ResponseWrapper(localName = "Checkin_stuResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CheckinStuResponse")
    public String checkinStu(
        @WebParam(name = "authcode", targetNamespace = "http://murpcn.com/murpwebservice/")
        String authcode,
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid,
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "longitude", targetNamespace = "http://murpcn.com/murpwebservice/")
        String longitude,
        @WebParam(name = "latitude", targetNamespace = "http://murpcn.com/murpwebservice/")
        String latitude);

    /**
     * 课堂点名-关闭点名签到
     * 
     * @param umcid
     * @param qdid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CloseDmqd", action = "http://murpcn.com/murpwebservice/CloseDmqd")
    @WebResult(name = "CloseDmqdResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "CloseDmqd", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CloseDmqd")
    @ResponseWrapper(localName = "CloseDmqdResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CloseDmqdResponse")
    public String closeDmqd(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "qdid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdid);

    /**
     * 课堂点名-点名统计
     * 
     * @param umcid
     * @param qdid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DmStatistics", action = "http://murpcn.com/murpwebservice/DmStatistics")
    @WebResult(name = "DmStatisticsResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "DmStatistics", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmStatistics")
    @ResponseWrapper(localName = "DmStatisticsResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmStatisticsResponse")
    public String dmStatistics(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "qdid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdid);

    /**
     * 课堂点名-[老师批量补签]
     * 
     * @param umcid
     * @param studentlist
     * @param qdTid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Checkin_dm_plqd", action = "http://murpcn.com/murpwebservice/Checkin_dm_plqd")
    @WebResult(name = "Checkin_dm_plqdResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Checkin_dm_plqd", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CheckinDmPlqd")
    @ResponseWrapper(localName = "Checkin_dm_plqdResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CheckinDmPlqdResponse")
    public String checkinDmPlqd(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "studentlist", targetNamespace = "http://murpcn.com/murpwebservice/")
        String studentlist,
        @WebParam(name = "qd_tid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdTid);

    /**
     * 课堂点名-重新发起签到
     * 
     * @param qdztid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "DmResign", action = "http://murpcn.com/murpwebservice/DmResign")
    @WebResult(name = "DmResignResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "DmResign", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmResign")
    @ResponseWrapper(localName = "DmResignResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.DmResignResponse")
    public ArrayOfPublicStruct dmResign(
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid);

    /**
     * 课堂点名-获取未签到学生
     * 
     * @param bjbh
     * @param umcid
     * @param qdztid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetUnsignedStu", action = "http://murpcn.com/murpwebservice/GetUnsignedStu")
    @WebResult(name = "GetUnsignedStuResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetUnsignedStu", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetUnsignedStu")
    @ResponseWrapper(localName = "GetUnsignedStuResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetUnsignedStuResponse")
    public ArrayOfPublicStruct getUnsignedStu(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid,
        @WebParam(name = "bjbh", targetNamespace = "http://murpcn.com/murpwebservice/")
        String bjbh);

    /**
     * 讲座签到-查看讲座列表
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetJzlb", action = "http://murpcn.com/murpwebservice/GetJzlb")
    @WebResult(name = "GetJzlbResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetJzlb", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetJzlb")
    @ResponseWrapper(localName = "GetJzlbResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetJzlbResponse")
    public ArrayOfPublicStruct getJzlb(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid);

    /**
     * 讲座签到-发起讲座签到(获取验证码)
     * 
     * @param jzbh
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetjzAuthCode", action = "http://murpcn.com/murpwebservice/GetjzAuthCode")
    @WebResult(name = "GetjzAuthCodeResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetjzAuthCode", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetjzAuthCode")
    @ResponseWrapper(localName = "GetjzAuthCodeResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetjzAuthCodeResponse")
    public ArrayOfPublicStruct getjzAuthCode(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "jzbh", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jzbh);

    /**
     * 讲座签到-学生获取讲座签到状态
     * 
     * @param jzbh
     * @param umcid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JzStuGetState", action = "http://murpcn.com/murpwebservice/JzStuGetState")
    @WebResult(name = "JzStuGetStateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "JzStuGetState", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzStuGetState")
    @ResponseWrapper(localName = "JzStuGetStateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzStuGetStateResponse")
    public String jzStuGetState(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "jzbh", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jzbh);

    /**
     * 讲座签到-教师获取讲座签到状态
     * 
     * @param jzbh
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "JzTeaGetState", action = "http://murpcn.com/murpwebservice/JzTeaGetState")
    @WebResult(name = "JzTeaGetStateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "JzTeaGetState", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzTeaGetState")
    @ResponseWrapper(localName = "JzTeaGetStateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzTeaGetStateResponse")
    public ArrayOfPublicStruct jzTeaGetState(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "jzbh", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jzbh);

    /**
     * 讲座签到-学生签到
     * 
     * @param authcode
     * @param umcid
     * @param qdztid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "jz_checkin", action = "http://murpcn.com/murpwebservice/jz_checkin")
    @WebResult(name = "jz_checkinResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "jz_checkin", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzCheckin")
    @ResponseWrapper(localName = "jz_checkinResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzCheckinResponse")
    public String jzCheckin(
        @WebParam(name = "authcode", targetNamespace = "http://murpcn.com/murpwebservice/")
        String authcode,
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid,
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid);

    /**
     * 讲座签到-关闭讲座签到--合并统计
     * 
     * @param umcid
     * @param qdztid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CloseJzqd", action = "http://murpcn.com/murpwebservice/CloseJzqd")
    @WebResult(name = "CloseJzqdResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "CloseJzqd", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CloseJzqd")
    @ResponseWrapper(localName = "CloseJzqdResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.CloseJzqdResponse")
    public String closeJzqd(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid);

    /**
     * 讲座签到-签到统计
     * 
     * @param umcid
     * @param qdztid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "JzStatistics", action = "http://murpcn.com/murpwebservice/JzStatistics")
    @WebResult(name = "JzStatisticsResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "JzStatistics", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzStatistics")
    @ResponseWrapper(localName = "JzStatisticsResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzStatisticsResponse")
    public String jzStatistics(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid,
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid);

    /**
     * 讲座签到-重新发起签到
     * 
     * @param qdztid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "JzResign", action = "http://murpcn.com/murpwebservice/JzResign")
    @WebResult(name = "JzResignResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "JzResign", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzResign")
    @ResponseWrapper(localName = "JzResignResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.JzResignResponse")
    public ArrayOfPublicStruct jzResign(
        @WebParam(name = "qdztid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String qdztid);

    /**
     * 获得新闻详细内容（链接地址）
     * 
     * @param newsId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetNewsDetail", action = "http://murpcn.com/murpwebservice/GetNewsDetail")
    @WebResult(name = "GetNewsDetailResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetNewsDetail", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetNewsDetail")
    @ResponseWrapper(localName = "GetNewsDetailResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetNewsDetailResponse")
    public String getNewsDetail(
        @WebParam(name = "newsId", targetNamespace = "http://murpcn.com/murpwebservice/")
        int newsId);

    /**
     * 获得新闻列表；newsId=起始新闻id号；topNum=翻页数，正数上翻页，负数下翻页
     * 
     * @param newsId
     * @param topNum
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetNewsList", action = "http://murpcn.com/murpwebservice/GetNewsList")
    @WebResult(name = "GetNewsListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetNewsList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetNewsList")
    @ResponseWrapper(localName = "GetNewsListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetNewsListResponse")
    public ArrayOfPublicStruct getNewsList(
        @WebParam(name = "newsId", targetNamespace = "http://murpcn.com/murpwebservice/")
        int newsId,
        @WebParam(name = "topNum", targetNamespace = "http://murpcn.com/murpwebservice/")
        int topNum);

    /**
     * 表格课表数据（按校历）
     * 
     * @param umcid
     * @param type
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetScheduleList", action = "http://murpcn.com/murpwebservice/GetScheduleList")
    @WebResult(name = "GetScheduleListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetScheduleList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetScheduleList")
    @ResponseWrapper(localName = "GetScheduleListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetScheduleListResponse")
    public ArrayOfPublicStruct getScheduleList(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "type", targetNamespace = "http://murpcn.com/murpwebservice/")
        String type);

    /**
     * 考试安排（最近考试安排）
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "Exam", action = "http://murpcn.com/murpwebservice/Exam")
    @WebResult(name = "ExamResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Exam", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.Exam")
    @ResponseWrapper(localName = "ExamResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ExamResponse")
    public ArrayOfPublicStruct exam(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 我的成绩（本学期考试成绩）
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "Mark", action = "http://murpcn.com/murpwebservice/Mark")
    @WebResult(name = "MarkResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Mark", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.Mark")
    @ResponseWrapper(localName = "MarkResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.MarkResponse")
    public ArrayOfPublicStruct mark(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 历史成绩
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetMyGrades", action = "http://murpcn.com/murpwebservice/GetMyGrades")
    @WebResult(name = "GetMyGradesResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetMyGrades", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetMyGrades")
    @ResponseWrapper(localName = "GetMyGradesResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetMyGradesResponse")
    public ArrayOfPublicStruct getMyGrades(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 自习教室（上午空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomMorning", action = "http://murpcn.com/murpwebservice/ClassroomMorning")
    @WebResult(name = "ClassroomMorningResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomMorning", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomMorning")
    @ResponseWrapper(localName = "ClassroomMorningResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomMorningResponse")
    public ArrayOfPublicStruct classroomMorning(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 自习教室（下午空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomAfternoon", action = "http://murpcn.com/murpwebservice/ClassroomAfternoon")
    @WebResult(name = "ClassroomAfternoonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomAfternoon", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomAfternoon")
    @ResponseWrapper(localName = "ClassroomAfternoonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomAfternoonResponse")
    public ArrayOfPublicStruct classroomAfternoon(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 自习教室（晚上空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomNight", action = "http://murpcn.com/murpwebservice/ClassroomNight")
    @WebResult(name = "ClassroomNightResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomNight", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNight")
    @ResponseWrapper(localName = "ClassroomNightResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNightResponse")
    public ArrayOfPublicStruct classroomNight(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 自习教室（全天空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomDay", action = "http://murpcn.com/murpwebservice/ClassroomDay")
    @WebResult(name = "ClassroomDayResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomDay", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomDay")
    @ResponseWrapper(localName = "ClassroomDayResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomDayResponse")
    public ArrayOfPublicStruct classroomDay(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 自习教室（明天空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomNextday", action = "http://murpcn.com/murpwebservice/ClassroomNextday")
    @WebResult(name = "ClassroomNextdayResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomNextday", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNextday")
    @ResponseWrapper(localName = "ClassroomNextdayResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNextdayResponse")
    public ArrayOfPublicStruct classroomNextday(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 自习教室（下节课空余自习教室）
     * 
     * @param umcid
     * @param jsmc
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "ClassroomNextlesoon", action = "http://murpcn.com/murpwebservice/ClassroomNextlesoon")
    @WebResult(name = "ClassroomNextlesoonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "ClassroomNextlesoon", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNextlesoon")
    @ResponseWrapper(localName = "ClassroomNextlesoonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.ClassroomNextlesoonResponse")
    public ArrayOfPublicStruct classroomNextlesoon(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid,
        @WebParam(name = "jsmc", targetNamespace = "http://murpcn.com/murpwebservice/")
        String jsmc);

    /**
     * 学习状态（和我的学籍合并一起）
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "StudyState", action = "http://murpcn.com/murpwebservice/StudyState")
    @WebResult(name = "StudyStateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "StudyState", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.StudyState")
    @ResponseWrapper(localName = "StudyStateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.StudyStateResponse")
    public ArrayOfPublicStruct studyState(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 下学期课（下学期预开课信息）
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "NexttermyLesson", action = "http://murpcn.com/murpwebservice/NexttermyLesson")
    @WebResult(name = "NexttermyLessonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "NexttermyLesson", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.NexttermyLesson")
    @ResponseWrapper(localName = "NexttermyLessonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.NexttermyLessonResponse")
    public ArrayOfPublicStruct nexttermyLesson(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * MURP获得部门联系方式----有分页，每页20条
     * 
     * @param mcid
     * @param page
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfGroupName
     */
    @WebMethod(operationName = "GetDeptPhoneByPage_S", action = "http://murpcn.com/murpwebservice/GetDeptPhoneByPage_S")
    @WebResult(name = "GetDeptPhoneByPage_SResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetDeptPhoneByPage_S", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetDeptPhoneByPageS")
    @ResponseWrapper(localName = "GetDeptPhoneByPage_SResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetDeptPhoneByPageSResponse")
    public ArrayOfGroupName getDeptPhoneByPageS(
        @WebParam(name = "mcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int mcid,
        @WebParam(name = "page", targetNamespace = "http://murpcn.com/murpwebservice/")
        int page);

    /**
     * 我的秘书
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "Sec", action = "http://murpcn.com/murpwebservice/Sec")
    @WebResult(name = "SecResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Sec", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.Sec")
    @ResponseWrapper(localName = "SecResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.SecResponse")
    public ArrayOfPublicStruct sec(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 日程安排----模块id为1：今明活动（讲座，社团等）；模块id为2：今日课程；模块id为3：明日课程；模块id为4：最新考试安排；
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTodayList", action = "http://murpcn.com/murpwebservice/GetTodayList")
    @WebResult(name = "GetTodayListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTodayList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTodayList")
    @ResponseWrapper(localName = "GetTodayListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTodayListResponse")
    public ArrayOfPublicStruct getTodayList(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-我的秘书
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "TeacherSec", action = "http://murpcn.com/murpwebservice/TeacherSec")
    @WebResult(name = "TeacherSecResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "TeacherSec", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.TeacherSec")
    @ResponseWrapper(localName = "TeacherSecResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.TeacherSecResponse")
    public ArrayOfPublicStruct teacherSec(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-下节课程
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeacherNextLesson", action = "http://murpcn.com/murpwebservice/GetTeacherNextLesson")
    @WebResult(name = "GetTeacherNextLessonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeacherNextLesson", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherNextLesson")
    @ResponseWrapper(localName = "GetTeacherNextLessonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherNextLessonResponse")
    public ArrayOfPublicStruct getTeacherNextLesson(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-监考安排(所有)
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeacherinvigilate", action = "http://murpcn.com/murpwebservice/GetTeacherinvigilate")
    @WebResult(name = "GetTeacherinvigilateResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeacherinvigilate", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherinvigilate")
    @ResponseWrapper(localName = "GetTeacherinvigilateResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherinvigilateResponse")
    public ArrayOfPublicStruct getTeacherinvigilate(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-可接任务-下学期任务
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeacherNextTermLesson", action = "http://murpcn.com/murpwebservice/GetTeacherNextTermLesson")
    @WebResult(name = "GetTeacherNextTermLessonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeacherNextTermLesson", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherNextTermLesson")
    @ResponseWrapper(localName = "GetTeacherNextTermLessonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherNextTermLessonResponse")
    public ArrayOfPublicStruct getTeacherNextTermLesson(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-工作总量
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeacherWorkHour", action = "http://murpcn.com/murpwebservice/GetTeacherWorkHour")
    @WebResult(name = "GetTeacherWorkHourResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeacherWorkHour", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherWorkHour")
    @ResponseWrapper(localName = "GetTeacherWorkHourResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherWorkHourResponse")
    public ArrayOfPublicStruct getTeacherWorkHour(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-教评信息
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "Getjiaopingxinxi", action = "http://murpcn.com/murpwebservice/Getjiaopingxinxi")
    @WebResult(name = "GetjiaopingxinxiResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "Getjiaopingxinxi", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.Getjiaopingxinxi")
    @ResponseWrapper(localName = "GetjiaopingxinxiResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetjiaopingxinxiResponse")
    public ArrayOfPublicStruct getjiaopingxinxi(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-开课信息
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeacherTermLesson", action = "http://murpcn.com/murpwebservice/GetTeacherTermLesson")
    @WebResult(name = "GetTeacherTermLessonResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeacherTermLesson", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherTermLesson")
    @ResponseWrapper(localName = "GetTeacherTermLessonResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeacherTermLessonResponse")
    public ArrayOfPublicStruct getTeacherTermLesson(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 教师-所教课程考试安排
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetTeachExamPlan", action = "http://murpcn.com/murpwebservice/GetTeachExamPlan")
    @WebResult(name = "GetTeachExamPlanResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetTeachExamPlan", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeachExamPlan")
    @ResponseWrapper(localName = "GetTeachExamPlanResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetTeachExamPlanResponse")
    public ArrayOfPublicStruct getTeachExamPlan(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int umcid);

    /**
     * 搜索学生信息(无分页，返回30条数据)
     * 
     * @param mcid
     * @param type
     * @param xhOrXm
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfProg
     */
    @WebMethod(operationName = "SearchStudent", action = "http://murpcn.com/murpwebservice/SearchStudent")
    @WebResult(name = "SearchStudentResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "SearchStudent", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.SearchStudent")
    @ResponseWrapper(localName = "SearchStudentResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.SearchStudentResponse")
    public ArrayOfProg searchStudent(
        @WebParam(name = "mcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        int mcid,
        @WebParam(name = "type", targetNamespace = "http://murpcn.com/murpwebservice/")
        String type,
        @WebParam(name = "xh_or_xm", targetNamespace = "http://murpcn.com/murpwebservice/")
        String xhOrXm);

    /**
     * 根据课程id获取课程进度_20141011(查无数据)
     * 
     * @param kcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.ArrayOfPublicStruct
     */
    @WebMethod(operationName = "GetLessonProgressList", action = "http://murpcn.com/murpwebservice/GetLessonProgressList")
    @WebResult(name = "GetLessonProgressListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetLessonProgressList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetLessonProgressList")
    @ResponseWrapper(localName = "GetLessonProgressListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetLessonProgressListResponse")
    public ArrayOfPublicStruct getLessonProgressList(
        @WebParam(name = "kcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String kcid);

    /**
     * PC端:用户搜索
     * 
     * @param speciality
     * @param useraccount
     * @param username
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.RI
     */
    @WebMethod(operationName = "SearchUser", action = "http://murpcn.com/murpwebservice/SearchUser")
    @WebResult(name = "SearchUserResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "SearchUser", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.SearchUser")
    @ResponseWrapper(localName = "SearchUserResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.SearchUserResponse")
    public RI searchUser(
        @WebParam(name = "useraccount", targetNamespace = "http://murpcn.com/murpwebservice/")
        String useraccount,
        @WebParam(name = "username", targetNamespace = "http://murpcn.com/murpwebservice/")
        String username,
        @WebParam(name = "speciality", targetNamespace = "http://murpcn.com/murpwebservice/")
        String speciality);

    /**
     * PC端:根据院系A-专业S-年级G筛选学生
     * 
     * @param specilitycode
     * @param academycode
     * @param grade
     * @param classcode
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.RI
     */
    @WebMethod(operationName = "GetStudentListByASG", action = "http://murpcn.com/murpwebservice/GetStudentListByASG")
    @WebResult(name = "GetStudentListByASGResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetStudentListByASG", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetStudentListByASG")
    @ResponseWrapper(localName = "GetStudentListByASGResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetStudentListByASGResponse")
    public RI getStudentListByASG(
        @WebParam(name = "academycode", targetNamespace = "http://murpcn.com/murpwebservice/")
        String academycode,
        @WebParam(name = "specilitycode", targetNamespace = "http://murpcn.com/murpwebservice/")
        String specilitycode,
        @WebParam(name = "grade", targetNamespace = "http://murpcn.com/murpwebservice/")
        String grade,
        @WebParam(name = "classcode", targetNamespace = "http://murpcn.com/murpwebservice/")
        String classcode);

    /**
     * PC端:获取院系-专业
     * 
     * @param umcid
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.RI
     */
    @WebMethod(operationName = "GetASList", action = "http://murpcn.com/murpwebservice/GetASList")
    @WebResult(name = "GetASListResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetASList", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetASList")
    @ResponseWrapper(localName = "GetASListResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetASListResponse")
    public RI getASList(
        @WebParam(name = "umcid", targetNamespace = "http://murpcn.com/murpwebservice/")
        String umcid);

    /**
     * 学生信息核对
     * 
     * @param xh
     * @return
     *     returns cn.tellyouwhat.gradeteller.murpnewsservice.PublicStruct
     */
    @WebMethod(operationName = "GetStudentInfo", action = "http://murpcn.com/murpwebservice/GetStudentInfo")
    @WebResult(name = "GetStudentInfoResult", targetNamespace = "http://murpcn.com/murpwebservice/")
    @RequestWrapper(localName = "GetStudentInfo", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetStudentInfo")
    @ResponseWrapper(localName = "GetStudentInfoResponse", targetNamespace = "http://murpcn.com/murpwebservice/", className = "cn.tellyouwhat.gradeteller.murpnewsservice.GetStudentInfoResponse")
    public PublicStruct getStudentInfo(
        @WebParam(name = "xh", targetNamespace = "http://murpcn.com/murpwebservice/")
        String xh);

}
