
package cn.tellyouwhat.gradeteller.murpnewsservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MURPNewsService", targetNamespace = "http://murpcn.com/murpwebservice/", wsdlLocation = "http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL")
public class MURPNewsService
    extends Service
{

    private final static URL MURPNEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MURPNEWSSERVICE_EXCEPTION;
    private final static QName MURPNEWSSERVICE_QNAME = new QName("http://murpcn.com/murpwebservice/", "MURPNewsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://219.245.18.61:81/KEY/MURPNewsService.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MURPNEWSSERVICE_WSDL_LOCATION = url;
        MURPNEWSSERVICE_EXCEPTION = e;
    }

    public MURPNewsService() {
        super(__getWsdlLocation(), MURPNEWSSERVICE_QNAME);
    }

    public MURPNewsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MURPNEWSSERVICE_QNAME, features);
    }

    public MURPNewsService(URL wsdlLocation) {
        super(wsdlLocation, MURPNEWSSERVICE_QNAME);
    }

    public MURPNewsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MURPNEWSSERVICE_QNAME, features);
    }

    public MURPNewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MURPNewsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MURPNewsServiceSoap
     */
    @WebEndpoint(name = "MURPNewsServiceSoap")
    public MURPNewsServiceSoap getMURPNewsServiceSoap() {
        return super.getPort(new QName("http://murpcn.com/murpwebservice/", "MURPNewsServiceSoap"), MURPNewsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MURPNewsServiceSoap
     */
    @WebEndpoint(name = "MURPNewsServiceSoap")
    public MURPNewsServiceSoap getMURPNewsServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://murpcn.com/murpwebservice/", "MURPNewsServiceSoap"), MURPNewsServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns MURPNewsServiceSoap
     */
    @WebEndpoint(name = "MURPNewsServiceSoap12")
    public MURPNewsServiceSoap getMURPNewsServiceSoap12() {
        return super.getPort(new QName("http://murpcn.com/murpwebservice/", "MURPNewsServiceSoap12"), MURPNewsServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MURPNewsServiceSoap
     */
    @WebEndpoint(name = "MURPNewsServiceSoap12")
    public MURPNewsServiceSoap getMURPNewsServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://murpcn.com/murpwebservice/", "MURPNewsServiceSoap12"), MURPNewsServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MURPNEWSSERVICE_EXCEPTION!= null) {
            throw MURPNEWSSERVICE_EXCEPTION;
        }
        return MURPNEWSSERVICE_WSDL_LOCATION;
    }

}
